# Site Settings
lang: en

title: Spack Cache

url: ""
baseurl: "/cache.spack.io"

permalink: /:year-:month-:day-:title/

# social media
twitter: spackpm
github_org: spack
github_repo: cache.spack.io

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - tailwind.css
  - generate_cache.py
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - spack-db
  - venv

livereload: true


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: true
  -
    scope:
      path: "_cache"
      type: "cache"
    values:
      layout: cache


markdown: kramdown
highlighter: rouge

# Collections
collections:
  cache:
    output: true
    permalink: /package/:path/
