all:
  compiler_count: '4'
  count: 2801
  parameter_count: '395'
  version: all
develop:
  arches:
    compiler: {}
    platform:
      linux: 58179
    platform_os:
      ubuntu18.04: 58179
    target:
      x86_64: 58179
  compiler_count: '4'
  compilers:
    clang@7.0.0: 4
    gcc@6.5.0: 1
    gcc@7.5.0: 56624
    gcc@8.4.0: 1550
  count: 1749
  parameter_count: '395'
  parameters:
    ARKODE: 6
    CVODE: 6
    CVODES: 6
    IDA: 6
    IDAS: 6
    KINSOL: 6
    abi: 1594
    addr2line: 1
    adiak: 6
    adios2: 31
    al: 10
    amesos: 11
    amesos2: 13
    anasazi: 11
    api: 103
    app: 15
    armci: 2
    arpack: 4
    ascent: 2
    ascent_types: 19
    async_api: 20
    atomic: 49
    auto-mount: 5
    auto_swap: 1
    avx2: 33
    aztec: 11
    backend: 41
    bbapi: 20
    belos: 13
    binutils: 3
    blas: 149
    blosc: 31
    blt_find_mpi: 45
    bmi: 6
    boost: 8
    boostsys: 13
    bootstrap: 1
    bsws: 38
    build_edition: 4
    build_type: 1988
    buildtype: 66
    butterflypack: 4
    bz2: 1372
    bzip2: 1431
    bzlib: 3
    c: 16
    c_interface: 4
    cache_base: 8
    caliper_detail: 2
    certs: 1517
    ch3_rank_bits: 58
    checksum: 13
    chrono: 49
    cinema: 2
    clang: 32
    clanguage: 14
    cntl_base: 8
    column_metadata: 1374
    compiler-rt: 32
    components: 40
    compression: 1535
    compute: 15
    conduit: 11
    conduits: 1
    container: 12
    copy_config: 8
    cpanm: 1567
    cpp: 4
    cpp14: 4
    cppflags: 2
    cross: 2
    crypto: 96
    cstd: 6
    ctypes: 1372
    cuda: 64
    cuda_arch: 58
    cuda_native: 2
    curses: 1383
    cxx: 1577
    cxxstd: 160
    darshan: 2
    dataman: 10
    datatype-engine: 271
    date_time: 49
    dbm: 1372
    debugalloc: 5
    default_library: 66
    development_files: 4
    device: 271
    device_alloc: 9
    dihydrogen: 2
    dimensions: 4
    dims: 15
    docs: 40
    double: 14
    doubleprecision: 19
    dray: 4
    dtcmp: 4
    dtype: 2
    dynamic_extensions: 1374
    elf: 3
    ensurepip: 1372
    epetra: 13
    epetraext: 11
    example: 12
    examples: 46
    examples-install: 6
    exception: 44
    execspace_cuda: 3
    execspace_openmp: 3
    execspace_serial: 3
    execspace_threads: 3
    exercises: 14
    explicit_template_instantiation: 11
    external_cinch: 2
    extras: 4
    fabrics: 422
    faodel: 2
    fetcher: 12
    ffmpeg: 2
    fftw: 2
    file_lock: 44
    file_systems: 58
    filesystem: 49
    flang: 2
    fonts: 15
    fortran: 501
    fpzip: 8
    ft: 18
    fts: 1374
    gasnet_root: 1
    generic-math: 6
    git: 1383
    glx: 22
    gmock: 3
    gobject: 18
    gold: 71
    gotcha: 6
    gotype: 13
    gpl: 3
    gptune: 6
    graph: 46
    gui: 16
    hdf5: 108
    hdf5_compat: 14
    headers: 14
    hl: 86
    host: 2
    hpctoolkit: 3
    hwloc: 274
    hydra: 271
    hypre: 14
    hzip: 8
    iconv: 96
    ifpack: 11
    ifpack2: 13
    image: 20
    instrumentation: 4
    int64: 6
    internal_unwind: 32
    intrepid: 8
    intrepid2: 8
    io: 3
    iostreams: 30
    isorropia: 8
    jpeg: 30
    kernel_lib: 2
    kim: 2
    kits: 4
    kokkos: 13
    languages: 1
    lapack: 141
    lapacke: 4
    layouts: 3
    ld: 39
    lex: 100
    lib: 17
    libbsd: 1513
    libcxx: 32
    libdl: 1
    libdw: 6
    libdwarf: 3
    libiberty: 14
    libidn2: 7
    libomptarget: 4
    libs: 5237
    libsodium: 91
    libunwind: 14
    libxml2: 3418
    libyaml: 33
    libyogrt: 8
    linear_solvers: 4
    lld: 32
    lldb: 32
    llvm: 22
    llvm_dylib: 2
    locale: 34
    localstatedir: 17
    locking: 230
    log: 38
    logging: 5
    logging-level: 6
    lua: 4
    lz4: 2
    lzma: 1372
    malloc: 4
    man: 5
    math: 40
    max_array_rank: 4
    max_cpu_count: 4
    max_dims: 1
    max_fields: 1
    memspace_cudaspace: 3
    memspace_cudauvmspace: 3
    metis: 28
    minitensor: 8
    ml: 11
    mlir: 2
    mpi: 612
    mpispawn: 3
    mpithreadmultiple: 15
    muelu: 13
    multibyte: 98
    multithreaded: 76
    ncurses: 504
    netaccessor: 3
    netcdf4: 7
    netmod: 271
    network: 6
    networking: 4
    nls: 40
    nox: 10
    offsets: 3
    ofi: 13
    omp_as_runtime: 26
    opengl: 34
    opengl2: 10
    openmp: 155
    openmp_blas: 8
    openpmd: 15
    openssl: 83
    optimize: 1629
    ordinals: 3
    otf2: 3
    outlev: 2
    output_level: 1
    ownlibs: 417
    papi: 11
    paraview: 2
    parmetis: 28
    patches: 6868
    pci: 663
    pdf: 18
    pdsh: 4
    pdt: 3
    perf: 10
    perl: 5
    petsc: 2
    pfe: 2
    phalanx: 8
    pic: 4311
    piro: 8
    plots: 6
    plugins: 39
    pmi: 271
    pmi_backwards_compatibility: 79
    pnetcdf: 2
    png: 39
    polly: 32
    precision: 46
    process_managers: 58
    profiling: 11
    program_options: 42
    programs: 1535
    psatd: 15
    pthreads: 9
    pyexpat: 1372
    python: 44
    python3: 4
    pythoncmd: 1372
    qed: 15
    qt: 10
    raja: 4
    random: 30
    random_access: 11
    readline: 1388
    redis: 4
    regcache: 58
    regex: 40
    rendering: 19
    resource_manager: 8
    rol: 8
    romio: 347
    rsh: 76
    rtree: 1374
    rythmos: 8
    sacado: 11
    sampler: 6
    scalars: 3
    scamac: 2
    scheduler: 17
    schedulers: 76
    scr: 2
    scr_config: 8
    serial: 38
    serialization: 43
    serializer: 5
    serve: 45
    shards: 8
    shared: 7962
    shylu: 8
    signals: 30
    sigsegv: 526
    silo: 6
    simmodsuite: 2
    simmodsuite_version_check: 2
    single_header: 3
    skip-tcsetpgrp-test: 6
    sm: 13
    spath: 5
    sql: 12
    sqlalchemy: 4
    sqlite3: 1372
    ssc: 29
    ssh: 9
    ssl: 1384
    sst: 29
    stack_size: 1
    stackguard: 10
    stackstart: 1
    stacktrace: 10
    staging: 2
    static: 97
    static_modules: 9
    std: 11
    stk: 8
    stl: 1569
    stokhos: 8
    stratimikos: 10
    subtree: 5
    superlu-dist: 22
    symbol_suffix: 230
    symbols: 2
    sysconfdir: 16
    system: 62
    sz: 33
    tar: 1383
    targets: 32
    tcmalloc: 5
    teko: 8
    tempus: 8
    termlib: 1594
    test: 62
    testlib: 11
    tests: 60
    thread: 62
    threads: 1855
    thyra: 10
    timer: 59
    tls: 131
    tm: 18
    toml: 235
    tools: 119
    tpetra: 13
    tprof: 15
    tracing: 40
    transcoder: 3
    trilinos: 2
    trilinoscouplings: 8
    umpire: 4
    unifyfs: 2
    use_vtkm: 4
    utf: 74
    uuid: 1372
    veloc: 2
    version3: 3
    version_suffix: 32
    viewer: 2
    visibility: 76
    visit: 2
    vt: 76
    vtkh: 8
    vtkm: 2
    wave: 30
    weak_backtrace: 40
    wrapper: 6
    wrapper-rpath: 76
    wrapperrpath: 74
    xar: 96
    xz: 1417
    zfp: 37
    zip: 1386
    zlib: 1427
    zoltan: 8
    zoltan2: 8
  version: '6'
v0.18:
  arches:
    compiler: {}
    platform:
      linux: 31036
    platform_os:
      ubuntu18.04: 31036
    target:
      x86_64: 31036
  compiler_count: '4'
  compilers:
    clang@7.0.0: 4
    gcc@6.5.0: 1
    gcc@7.5.0: 30075
    gcc@8.4.0: 956
  count: 1052
  parameter_count: '395'
  parameters:
    ARKODE: 3
    CVODE: 3
    CVODES: 3
    IDA: 3
    IDAS: 3
    KINSOL: 3
    abi: 898
    addr2line: 1
    adiak: 3
    adios2: 14
    al: 5
    amesos: 6
    amesos2: 7
    anasazi: 6
    api: 55
    app: 6
    armci: 1
    arpack: 2
    ascent: 1
    ascent_types: 11
    async_api: 11
    atomic: 30
    auto-mount: 3
    auto_swap: 1
    avx2: 16
    aztec: 6
    backend: 19
    bbapi: 11
    belos: 7
    binutils: 1
    blas: 66
    blosc: 14
    blt_find_mpi: 23
    bmi: 3
    boost: 4
    boostsys: 8
    bootstrap: 1
    bsws: 19
    build_edition: 2
    build_type: 1119
    buildtype: 33
    butterflypack: 2
    bz2: 676
    bzip2: 710
    bzlib: 2
    c: 11
    c_interface: 2
    cache_base: 4
    caliper_detail: 1
    certs: 821
    ch3_rank_bits: 29
    checksum: 8
    chrono: 30
    cinema: 1
    clang: 16
    clanguage: 7
    cntl_base: 4
    column_metadata: 678
    compiler-rt: 16
    components: 21
    compression: 815
    compute: 6
    conduit: 6
    conduits: 1
    container: 9
    copy_config: 4
    cpanm: 871
    cpp: 2
    cpp14: 2
    cppflags: 2
    cross: 1
    crypto: 72
    cstd: 3
    ctypes: 676
    cuda: 39
    cuda_arch: 36
    cuda_native: 1
    curses: 687
    cxx: 878
    cxxstd: 89
    darshan: 1
    dataman: 5
    datatype-engine: 136
    date_time: 30
    dbm: 676
    debugalloc: 3
    default_library: 33
    development_files: 2
    device: 136
    device_alloc: 7
    dihydrogen: 1
    dimensions: 2
    dims: 6
    docs: 21
    double: 7
    doubleprecision: 11
    dray: 2
    dtcmp: 2
    dtype: 1
    dynamic_extensions: 678
    elf: 1
    ensurepip: 676
    epetra: 7
    epetraext: 6
    example: 6
    examples: 29
    examples-install: 3
    exception: 25
    execspace_cuda: 2
    execspace_openmp: 2
    execspace_serial: 2
    execspace_threads: 2
    exercises: 9
    explicit_template_instantiation: 6
    external_cinch: 1
    extras: 2
    fabrics: 234
    faodel: 1
    fetcher: 8
    ffmpeg: 1
    fftw: 1
    file_lock: 25
    file_systems: 29
    filesystem: 30
    flang: 1
    fonts: 8
    fortran: 254
    fpzip: 5
    ft: 9
    fts: 678
    gasnet_root: 1
    generic-math: 3
    git: 687
    glx: 11
    gmock: 2
    gobject: 9
    gold: 36
    gotcha: 3
    gotype: 7
    gpl: 2
    gptune: 2
    graph: 26
    gui: 8
    hdf5: 55
    hdf5_compat: 7
    headers: 7
    hl: 45
    host: 1
    hpctoolkit: 2
    hwloc: 138
    hydra: 136
    hypre: 7
    hzip: 5
    iconv: 72
    ifpack: 6
    ifpack2: 7
    image: 9
    instrumentation: 2
    int64: 3
    internal_unwind: 16
    intrepid: 4
    intrepid2: 4
    io: 1
    iostreams: 18
    isorropia: 4
    jpeg: 14
    kernel_lib: 1
    kim: 1
    kits: 2
    kokkos: 7
    languages: 1
    lapack: 62
    lapacke: 3
    layouts: 2
    ld: 20
    lex: 51
    lib: 7
    libbsd: 772
    libcxx: 16
    libdl: 1
    libdw: 3
    libdwarf: 1
    libiberty: 7
    libidn2: 3
    libomptarget: 2
    libs: 2939
    libsodium: 46
    libunwind: 7
    libxml2: 1719
    libyaml: 15
    libyogrt: 4
    linear_solvers: 2
    lld: 16
    lldb: 16
    llvm: 11
    llvm_dylib: 1
    locale: 20
    localstatedir: 9
    locking: 115
    log: 22
    logging: 3
    logging-level: 3
    lua: 2
    lz4: 1
    lzma: 676
    malloc: 2
    man: 3
    math: 23
    max_array_rank: 2
    max_cpu_count: 2
    max_dims: 1
    max_fields: 1
    memspace_cudaspace: 2
    memspace_cudauvmspace: 2
    metis: 14
    minitensor: 4
    ml: 6
    mlir: 1
    mpi: 312
    mpispawn: 1
    mpithreadmultiple: 6
    muelu: 7
    multibyte: 51
    multithreaded: 44
    ncurses: 302
    netaccessor: 2
    netcdf4: 4
    netmod: 136
    network: 4
    networking: 2
    nls: 24
    nox: 5
    offsets: 2
    ofi: 8
    omp_as_runtime: 13
    opengl: 17
    opengl2: 5
    openmp: 85
    openmp_blas: 4
    openpmd: 6
    openssl: 64
    optimize: 932
    ordinals: 2
    otf2: 1
    outlev: 1
    output_level: 1
    ownlibs: 236
    papi: 5
    paraview: 1
    parmetis: 14
    patches: 3770
    pci: 356
    pdf: 9
    pdsh: 2
    pdt: 1
    perf: 7
    perl: 3
    petsc: 1
    pfe: 1
    phalanx: 4
    pic: 2304
    piro: 4
    plots: 2
    plugins: 20
    pmi: 136
    pmi_backwards_compatibility: 60
    pnetcdf: 1
    png: 18
    polly: 16
    precision: 20
    process_managers: 29
    profiling: 7
    program_options: 24
    programs: 815
    psatd: 6
    pthreads: 5
    pyexpat: 676
    python: 21
    python3: 2
    pythoncmd: 676
    qed: 6
    qt: 5
    raja: 2
    random: 18
    random_access: 6
    readline: 684
    redis: 2
    regcache: 29
    regex: 23
    rendering: 11
    resource_manager: 4
    rol: 4
    romio: 193
    rsh: 57
    rtree: 678
    rythmos: 4
    sacado: 6
    sampler: 3
    scalars: 2
    scamac: 1
    scheduler: 10
    schedulers: 57
    scr: 1
    scr_config: 4
    serial: 21
    serialization: 25
    serializer: 3
    serve: 22
    shards: 4
    shared: 4352
    shylu: 4
    signals: 18
    sigsegv: 310
    silo: 3
    simmodsuite: 1
    simmodsuite_version_check: 1
    single_header: 2
    skip-tcsetpgrp-test: 4
    sm: 8
    spath: 3
    sql: 6
    sqlalchemy: 2
    sqlite3: 676
    ssc: 13
    ssh: 5
    ssl: 682
    sst: 13
    stack_size: 1
    stackguard: 7
    stackstart: 1
    stacktrace: 5
    staging: 1
    static: 68
    static_modules: 5
    std: 7
    stk: 4
    stl: 873
    stokhos: 4
    stratimikos: 5
    subtree: 3
    superlu-dist: 11
    symbol_suffix: 115
    symbols: 1
    sysconfdir: 8
    system: 37
    sz: 15
    tar: 687
    targets: 16
    tcmalloc: 3
    teko: 4
    tempus: 4
    termlib: 898
    test: 34
    testlib: 6
    tests: 34
    thread: 37
    threads: 1015
    thyra: 5
    timer: 35
    tls: 91
    tm: 11
    toml: 115
    tools: 63
    tpetra: 7
    tprof: 6
    tracing: 20
    transcoder: 2
    trilinos: 1
    trilinoscouplings: 4
    umpire: 2
    unifyfs: 1
    use_vtkm: 2
    utf: 39
    uuid: 676
    veloc: 1
    version3: 2
    version_suffix: 16
    viewer: 1
    visibility: 44
    visit: 1
    vt: 57
    vtkh: 4
    vtkm: 1
    wave: 18
    weak_backtrace: 21
    wrapper: 3
    wrapper-rpath: 57
    wrapperrpath: 37
    xar: 72
    xz: 705
    zfp: 17
    zip: 690
    zlib: 703
    zoltan: 4
    zoltan2: 4
  version: '6'
