name: Update Spack Cache Interface
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'
permissions:
   contents: write

jobs:
  extraction:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Clone development branch of spack
      run: git clone https://github.com/spack/spack /opt/spack
    - name: Run update script
      run: |
         export PATH=/opt/spack/bin:$PATH
         pip install -r requirements.txt
         # make directories first to ensure they exist to prevent find from failing
         mkdir -p _cache pages/tags _data
         spack python generate_cache.py

    - name: Push Results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add _cache pages/tags _data
        git commit -m "Automated push with new spack cache data $(date '+%Y-%m-%d')" || exit 0
        git push origin main
